name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install frontend dependencies
        run: npm ci
      - name: Lint frontend
        run: npm run lint --if-present
      - name: Run frontend tests
        run: npm test --if-present
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Rust backend (Tauri)
        run: |
          cd src-tauri
          cargo build --release
      - name: Run Rust tests
        run: |
          cd src-tauri
          cargo test --release
