name: 💡 Feature Request
description: Suggest a new feature or improvement for Graft
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas for making Graft better.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear description of the feature you'd like to see.
      placeholder: What feature would you like?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
        I often need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other ways to solve this problem?
      placeholder: Other approaches you've thought about...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples from other tools.
      placeholder: Paste images or describe UI ideas...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be useful
        - Very important
        - Critical for my workflow
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this?
      options:
        - No, just suggesting
        - I can help test it
        - I can help implement it
        - I would lead the implementation
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, related issues, or references?
      placeholder: Links to similar features, related discussions, etc...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues and this feature has not been requested
          required: true
        - label: This feature aligns with Graft's vision of a fast, keyboard-first Git GUI
          required: true
        - label: I have provided enough detail for others to understand the feature
          required: true
